export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    SET_LAUNCH_STATUS_FILTER: "SET_LAUNCH_STATUS_FILTER",
    SET_ROCKET_NAME: "SET_ROCKET_NAME"
};
