export const ActionTypes = {
    SET_MISSIONS: "SET_MISSIONS",

    SET_LAUNCH_STATUS_FILTER: "SET_LAUNCH_STATUS_FILTER",
    SET_UPCOMING_STATUS_FILTER: "SET_UPCOMING_STATUS_FILTER",
    SET_LAUNCH_DATE_FILTER: "SET_LAUNCH_DATE_FILTER",
    SET_ROCKET_NAME: "SET_ROCKET_NAME"
};
